// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package api — types.go：所有 API 响应的命名 struct。
字段顺序和 json tag 与前端消费的 JSON key 严格对齐。
此文件是 tygo 代码生成的数据源，改动后在 server/ 下运行 go generate . 同步 TS 类型。
*/

/**
 * CaptureReq 描述一次 HTTP 请求的请求侧数据。
 */
export interface CaptureReq {
  method?: string;
  headers?: { [key: string]: string};
  body?: string;
  size?: number /* int */;
  /**
   * Truncated 表示 body 在抓取时超过 captureBodyLimit 被截断（前端可提示用户）
   */
  truncated?: boolean;
}
/**
 * CaptureRes 描述一次 HTTP 请求的响应侧数据。
 */
export interface CaptureRes {
  statusCode?: number /* int */;
  statusMessage?: string;
  headers?: { [key: string]: string};
  body?: string;
  size?: number /* int */;
  truncated?: boolean;
}
/**
 * CaptureItem 是一次 HTTP 会话的完整快照，字段与前端 NetworkItem 一一对应。
 * 时间字段（StartTime / EndTime / DnsTime 等）均为 unix 毫秒绝对时间戳。
 */
export interface CaptureItem {
  id: string;
  url: string;
  hostname?: string;
  path?: string;
  protocol?: string;
  method?: string;
  /**
   * 注意 json tag 用小写 p，与前端 NetworkItem.clientIp 对齐
   */
  clientIp?: string;
  hostIp?: string;
  /**
   * 时间戳（unix ms）
   */
  startTime: number /* int64 */;
  endTime?: number /* int64 */;
  requestTime?: number /* int64 */; // 同 StartTime，兼容旧前端
  dnsTime?: number /* int64 */;
  httpsTime?: number /* int64 */;
  responseTime?: number /* int64 */;
  ttfb?: number /* int64 */;
  req: CaptureReq;
  res: CaptureRes;
  /**
   * 元数据
   */
  type?: string;
  contentEncoding?: string;
  appName?: string;
  reqError?: boolean;
  resError?: boolean;
  reqType?: string;
  resType?: string;
  /**
   * 高亮 + 备注（P0 特性）
   */
  highlighted?: boolean;
  comment?: string;
  /**
   * 进程归属（P1 特性）
   */
  processName?: string;
  processId?: number /* int */;
  /**
   * GraphQL 元数据（P1 特性）
   */
  graphqlOp?: string; // operationName（空表示非 GraphQL）
}
/**
 * CaptureData 按 id 索引抓包数据，供批量查询使用。
 * IDs 保持写入顺序，Data 按 id 索引供前端 O(1) 查找。
 */
export interface CaptureData {
  ids: string[];
  data: { [key: string]: CaptureItem | undefined};
}
/**
 * BatchCaptureRequest 是 POST /api/captures/batch 的请求体。
 */
export interface BatchCaptureRequest {
  ids: string[];
}
/**
 * ErrorResponse 用于 4xx/5xx 错误响应 body。
 */
export interface ErrorResponse {
  error: string;
}
/**
 * ServerInfo 出现在多个响应里，描述后端运行环境。
 */
export interface ServerInfo {
  hostname: string;
  go: string;
  platform: string;
}
/**
 * RulesListResponse 对应 GET /api/rules/enabled（全局状态）。
 */
export interface RulesListResponse {
  enabledCount: number /* int */;
  defaultRulesIsDisabled: boolean;
  defaultRules: string;
  allowMultipleChoice: boolean;
  backRulesFirst: boolean;
  list: any[];
}
/**
 * ValuesResponse 对应 init.values 字段。
 */
export interface ValuesResponse {
  list: any[];
}
/**
 * InitResponse 对应 GET /api/init。
 */
export interface InitResponse {
  wName: string;
  version: string;
  clientId: string;
  clientIp: string;
  lastDataId: number /* int64 */;
  lastSvrLogId: number /* int64 */;
  interceptHttpsConnects: boolean;
  enableHttp2: boolean;
  /**
   * ProxyAddr 是代理监听 host:port（来自 --addr 启动参数），前端用于 TopNav 监听状态徽章。
   */
  proxyAddr: string;
  server: ServerInfo;
  rules: RulesListResponse;
  values: ValuesResponse;
  plugins: { [key: string]: any};
  disabledPlugins: { [key: string]: any};
}
/**
 * StatusResponse 对应 GET /api/status。
 */
export interface StatusResponse {
  storage: string;
  piperName: string;
  name: string;
  version: string;
  uptime: number /* float64 */;
}
/**
 * HTTPSStatusResponse 对应 GET /api/https/status。
 */
export interface HTTPSStatusResponse {
  enableCapture: boolean;
  enableHttp2: boolean;
}
/**
 * RulesEnabledResponse 对应 GET /api/rules/enabled。
 */
export interface RulesEnabledResponse {
  mflag: string;
  list: any[];
}
/**
 * GetFramesResponse 对应 GET /api/captures/:id/frames。
 */
export interface GetFramesResponse {
  frames: any[];
}
/**
 * BypassRuleItem 是一条 bypass 规则。
 */
export interface BypassRuleItem {
  pattern: string;
  tag: string;
  enabled: boolean;
}
/**
 * DetectedHostItem 是检测到的 SSL Pinning 主机记录。
 */
export interface DetectedHostItem {
  host: string;
  failures: number /* int */;
  last_failure: string;
}
/**
 * BypassManager 是 bypass 规则存储的接口（api 层与 proxy 层解耦）。
 */
export type BypassManager = any;
/**
 * PinningManager 是 SSL Pinning 检测器的接口。
 */
export type PinningManager = any;
/**
 * ThrottlePreset 是限速档位名称。
 */
export type ThrottlePreset = string;
/**
 * ThrottleConfig 是 GET/PUT /api/throttle 的请求/响应体。
 */
export interface ThrottleConfig {
  preset: ThrottlePreset;
  upBps: number /* int64 */;
  downBps: number /* int64 */;
  latencyMs: number /* int64 */;
}
/**
 * NetworkInterface 表示一张可用于代理客户端连接的网卡条目。
 */
export interface NetworkInterface {
  name: string; // 网卡名（loopback 用 "loopback"）
  ip: string; // IPv4 字符串
  kind: string; // "loopback" | "lan"
}
/**
 * NetworkInterfacesResponse 对应 GET /api/network/interfaces。
 * 前端用它在「系统代理」面板里列出所有可设置的 host:port 组合。
 */
export interface NetworkInterfacesResponse {
  proxyHost: string; // 监听 host（空 / 0.0.0.0 表示全网卡）
  proxyPort: number /* int */; // 监听端口（真实 proxy 端口，不是 webui dev server 端口）
  interfaces: NetworkInterface[]; // loopback 在前，LAN 在后
}
